name: pertadapt
channels:
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - attr=2.5.1=h166bdaf_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-command-line-tools=12.9.0=0
  - cuda-compiler=12.9.0=0
  - cuda-crt-dev_linux-64=12.9.41=ha770c72_0
  - cuda-crt-tools=12.9.41=ha770c72_0
  - cuda-cudart=12.9.37=h5888daf_0
  - cuda-cudart-dev=12.9.37=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.37=h3f2d84a_0
  - cuda-cudart-static=12.9.37=h5888daf_0
  - cuda-cudart-static_linux-64=12.9.37=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.37=h3f2d84a_0
  - cuda-cuobjdump=12.9.26=hbd13f7d_0
  - cuda-cupti=12.9.19=h9ab20c4_0
  - cuda-cupti-dev=12.9.19=h9ab20c4_0
  - cuda-cuxxfilt=12.9.19=1
  - cuda-driver-dev=12.9.37=0
  - cuda-driver-dev_linux-64=12.9.37=0
  - cuda-gdb=12.9.19=1
  - cuda-libraries=12.9.0=0
  - cuda-libraries-dev=12.9.0=0
  - cuda-nsight=12.9.19=0
  - cuda-nvcc=12.9.41=0
  - cuda-nvcc-dev_linux-64=12.9.41=he91c749_0
  - cuda-nvcc-impl=12.9.41=h85509e4_0
  - cuda-nvcc-tools=12.9.41=he02047a_0
  - cuda-nvcc_linux-64=12.9.41=0
  - cuda-nvdisasm=12.9.19=hbd13f7d_0
  - cuda-nvml-dev=12.9.40=1
  - cuda-nvprof=12.9.19=0
  - cuda-nvprune=12.9.19=1
  - cuda-nvrtc=12.9.41=h5888daf_0
  - cuda-nvrtc-dev=12.9.41=h5888daf_0
  - cuda-nvtx=12.9.19=h5888daf_0
  - cuda-nvvm-dev_linux-64=12.9.41=ha770c72_0
  - cuda-nvvm-impl=12.9.41=he02047a_0
  - cuda-nvvm-tools=12.9.41=he02047a_0
  - cuda-nvvp=12.9.19=1
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.19=0
  - cuda-sanitizer-api=12.9.27=1
  - cuda-toolkit=12.9.0=0
  - cuda-tools=12.9.0=0
  - cuda-version=12.9=h4f385c5_3
  - cuda-visual-tools=12.9.0=0
  - cudnn=9.10.0.56=hcd2ec93_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.7.0=h5888daf_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.13.3=ha770c72_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.14.0.30=4
  - glib=2.84.1=h6287aef_1
  - glib-tools=2.84.1=h4833e2c_1
  - gmp=6.3.0=hac33072_2
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcublas=12.9.0.13=h9ab20c4_0
  - libcublas-dev=12.9.0.13=h9ab20c4_0
  - libcudnn=9.10.0.56=h4840ae0_0
  - libcudnn-dev=9.10.0.56=hcd2ec93_0
  - libcudss=0.5.0.16=h14340ca_1
  - libcufft=11.4.0.6=h5888daf_0
  - libcufft-dev=11.4.0.6=h5888daf_0
  - libcufile=1.14.0.30=h628e99a_0
  - libcufile-dev=1.14.0.30=h5888daf_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurand-dev=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.4.40=h9ab20c4_0
  - libcusolver-dev=11.7.4.40=h9ab20c4_0
  - libcusparse=12.5.9.5=h5888daf_0
  - libcusparse-dev=12.5.9.5=h5888daf_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.84.1=h3618099_1
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libmagma=2.9.0=h19665d7_1
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.4.0.27=0
  - libnpp-dev=12.4.0.27=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.9.19=0
  - libnvfatbin-dev=12.9.19=0
  - libnvjitlink=12.9.41=h5888daf_0
  - libnvjitlink-dev=12.9.41=h5888daf_0
  - libnvjpeg=12.4.0.16=0
  - libnvjpeg-dev=12.4.0.16=0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.29.3=h501fc15_1
  - libsqlite=3.49.2=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtorch=2.7.0=cuda126_generic_hc99dd11_200
  - libudev1=257.4=hbe16f8c_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.2=h65c71a3_0
  - libxml2=2.13.8=h81593ed_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.4=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py310h89163eb_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.26.5.1=ha44e49d_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - nsight-compute=2025.2.0.11=0
  - nspr=4.36=h5888daf_0
  - nss=3.111=h159eef7_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openssl=3.5.0=h7b32b05_1
  - optree=0.15.0=py310h3788b33_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=hc749103_0
  - pip=25.1.1=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - python=3.10.17=hd6af730_0_cpython
  - python_abi=3.10=6_cp310
  - pytorch=2.7.0=cuda126_generic_py310_hd77d226_200
  - pytorch-gpu=2.7.0=cuda126_generic_h9f17e3a_200
  - rdma-core=57.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - sleef=3.8=h1b44611_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - adpbulk==0.1.4
    - anndata==0.11.4
    - array-api-compat==1.12.0
    - cell-eval==0.6.5
    - certifi==2025.4.26
    - contourpy==1.3.2
    - cycler==0.12.1
    - dcor==0.6
    - exceptiongroup==1.3.0
    - flash-attn==2.7.4.post1
    - fonttools==4.60.1
    - formulaic==1.2.1
    - formulaic-contrasts==1.0.0
    - h5py==3.15.1
    - idna==3.10
    - igraph==1.0.0
    - iniconfig==2.3.0
    - interface-meta==1.3.0
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - legacy-api-wrap==1.5
    - llvmlite==0.45.1
    - matplotlib==3.10.7
    - modelgenerator==0.1.2
    - narwhals==2.10.2
    - natsort==8.4.0
    - ninja==1.11.1.4
    - numba==0.62.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.3.14
    - nvidia-cuda-cupti-cu12==12.8.57
    - nvidia-cuda-nvrtc-cu12==12.8.61
    - nvidia-cuda-runtime-cu12==12.8.57
    - nvidia-cudnn-cu12==9.7.1.26
    - nvidia-cufft-cu12==11.3.3.41
    - nvidia-cufile-cu12==1.13.0.11
    - nvidia-curand-cu12==10.3.9.55
    - nvidia-cusolver-cu12==11.7.2.55
    - nvidia-cusparse-cu12==12.5.7.53
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.8.55
    - pandas==2.3.3
    - patsy==1.0.2
    - pdex==0.1.25
    - pillow==12.0.0
    - pluggy==1.6.0
    - polars==1.35.2
    - polars-runtime-32==1.35.2
    - pyarrow==22.0.0
    - pydeseq2==0.5.2
    - pygments==2.19.2
    - pynndescent==0.5.13
    - pyparsing==3.2.5
    - pytest==9.0.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - scanpy==1.11.5
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - session-info==1.0.1
    - session-info2==0.2.3
    - six==1.17.0
    - statsmodels==0.14.5
    - stdlib-list==0.12.0
    - sympy==1.13.3
    - texttable==1.7.0
    - threadpoolctl==3.6.0
    - tomli==2.3.0
    - torch==2.7.0+cu128
    - torch-geometric==2.6.1
    - torchaudio==2.7.0+cu128
    - torchvision==0.22.0+cu128
    - tqdm==4.67.1
    - triton==3.3.0
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - umap-learn==0.5.9.post2
    - wrapt==2.0.1
    - xgboost==3.1.1
